### ISSUE TITLE
Multihack crashes server

### ISSUE THREAD

**Issue by Dejoylol** [TheBarrens/mangos-classic#53]
the problem: The program Multihack crashes the server about 50% of the time when booted up from a player on the server

what should happen: server shouldnt crash and well they are able to hack

how to reproduce: run program and watch server crash

http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-emulator-servers/wow-emu-programs/330718-multihack-vanilla-1-12-1-servers.html

**Comment by Tixlenra** [comment]
Confirmed it crashes the server. Booted it up 6 times, 3 of them times it crashed the server. 

![image](https://cloud.githubusercontent.com/assets/16974526/25803409/9b2b6f64-33ee-11e7-8613-ecab56ae8153.png)
